### PR TITLE
remove symlinks in crashReporter ios framework

### PR DESCRIPTION
**Pull request by coboshm**

### CODE REVIEW

**Review by gonzaloserrano — APPROVED** [review]

**Comment by am** [comment]
Does a native crash send the report to Rollbar?

**Review by am — COMMENTED** [review]
Does a native crash send the report to Rollbar?

**Comment by coboshm** [comment]
I just removed the crashReporter symlinks. it was causing an error during the ios build

https://github.com/Resgrid/cordova-plugins-rollbar/issues/13

**Comment by gonzaloserrano** [comment]
@am this PR just removes the symlinks.

How can we test whether the crashes go to rollbar or not?

**Comment by am** [comment]
@gonzaloserrano With the android reporter what I did was to read the source code of the plugin and find a place to make a simple call to Rollbar api using the reporter and see if it arrived the Rollbar servers.

**Pull request merged**
